src/main/java/edu/hm/hafner/analysis/Issue.java
src/main/java/edu/hm/hafner/analysis/Issues.java
src/test/java/edu/hm/hafner/analysis/IssueBuilderTest.java
src/test/java/edu/hm/hafner/analysis/IssueTest.java
src/test/java/edu/hm/hafner/analysis/IssuesTest.java
src/test/java/edu/hm/hafner/analysis/assertj/AnalysisSoftAssertions.java
src/test/java/edu/hm/hafner/analysis/assertj/IssueAssert.java
src/test/java/edu/hm/hafner/analysis/assertj/IssuesAssert.java

Using JUnit 5, AssertJ and soft assertions.

Added unit tests for Issue, IssueBuilder and Issues.

---

src/test/java/edu/hm/hafner/analysis/parser/CssLintParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/DiabCParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/DoxygenParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/DrMemoryParserTest.java

CssLintParserTest, DiabCParserTest, DoxygenParserTest and DrMemoryParserTest use AssertJ now.

ParserTests use AssertJ now.

---

.idea/inspectionProfiles/Ullrich_Hafner.xml
src/test/java/edu/hm/hafner/analysis/parser/Gcc4CompilerParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/Gcc4LinkerParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/GccParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/GendarmeParserTest.java

Updated 4 ParserTests
- Gcc4CompilerParserTest
- Gcc4LinkerParserTest
- GccParserTest
- GendarmeParserTest

Updated 4 ParserTests

---

src/test/java/edu/hm/hafner/analysis/parser/GoLintParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/GoVetParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/HpiCompileParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/IarParserTest.java

The following parser tests were changed to use assertj:
- GoLintParserTest
- GoVetParserTest
- HpiCompileParserTest
- IarParserTest

Changed parser tests to use Assertj.

---

src/test/java/edu/hm/hafner/analysis/parser/ClangParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/CodeAnalysisParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/CoolfluxChessccParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/CppLintParserTest.java

Converted test classes:
- ClangParserTest
- CodeAnalysisParserTest
- CoolfluxChessccParserTest
- CppLintParserTest

Converted parser tests to use AssertJ.

---

src/test/java/edu/hm/hafner/analysis/parser/IdeaInspectionParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/IntelParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/InvalidsParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/JSLintParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/JavaDocParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/JcReportParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/LinuxKernelOutputParserTest.java

Now in my repo because of rebase problems.
Nexus457:
- IdeaInspectionParserTest
- IntelParserTest
- InvalidsParserTest
- JavacParserTest
Johdeath:
- JavaDocParserTest.java
- JcReportParserTest.java
- JSLintParserTest.java
- LinuxKernelOutputParserTest.java

replaced junit 4 tests and replaced checkwarnings with softassertions of

---

src/test/java/edu/hm/hafner/analysis/parser/PREfastParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/PerlCriticParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/PhpParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/PuppetLintParserTest.java

Exchanged all Assertions with Soft and Custom Assertions.

Refactored Tests for PerlCriticParser, PhpParser, PREfastParser, PuppetLintParser

---

src/test/java/edu/hm/hafner/analysis/parser/CssLintParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/DiabCParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/DoxygenParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/DrMemoryParserTest.java

Changed for CssLintParserTest, DiabCParserTest, DoxygenParserTest, DrMemoryParserTest

Changed extension from ParserTest to AbstractParserTest

---

src/test/java/edu/hm/hafner/analysis/parser/PylintParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/QACSourceCodeAnalyserParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/RFLintParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/ResharperInspectCodeParserTest.java

Refactored tests for
- PylintParser
- QACSourceCodeAnalyserParser
- ResharperInspectCodeParser
- RFLintParser

Refactor parser tests to use abstract test class

---

src/test/java/edu/hm/hafner/analysis/parser/EclipseParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/ErlcParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/FlexSDKParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/FxcopParserTest.java

convert :
- EclipseParserTest
- ErlcParserTest 
- FlexSDKParserTest
- FxcopParserTest

Abstract Test Pattern for Parser

---

src/test/java/edu/hm/hafner/analysis/parser/GhsMultiParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/GnatParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/GnuFortranParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/GnuMakeGccParserTest.java

Changed base class from ParserTest to AbstractParserTest to enforce serialisation test by the abstract test pattern

Changed base class from ParserTest to AbstractParserTest

---

.idea/checkstyle-idea.xml
.idea/inspectionProfiles/Ullrich_Hafner.xml
src/test/java/edu/hm/hafner/analysis/parser/ClangParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/CodeAnalysisParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/CoolfluxChessccParserTest.java

Following Parser now uses AbstractParserTest as parent class:
ClangParserTest
CodeAnalysisParserTest
CoolfluxChessccParserTest

AbstractParserTest

---

src/main/java/edu/hm/hafner/analysis/XmlElementUtil.java
src/main/java/edu/hm/hafner/analysis/parser/TaglistParser.java
src/test/java/edu/hm/hafner/analysis/parser/TaglistParserTest.java
src/test/resources/edu/hm/hafner/analysis/parser/taglist.xml

Parser for Taglist Maven Plugin

---

src/main/java/edu/hm/hafner/analysis/parser/IarParser.java
src/test/java/edu/hm/hafner/analysis/parser/IarParserTest.java
src/test/resources/edu/hm/hafner/analysis/parser/issue55750.txt

after your comments I created a new commit with just this bugfix

[JENKINS-55750] Added test cases and fix warnings which could not been find

---

src/main/java/edu/hm/hafner/analysis/parser/AjcParser.java
src/main/java/edu/hm/hafner/analysis/parser/IarCstatParser.java
src/test/java/edu/hm/hafner/analysis/parser/IarCstatParserTest.java

I fixed some check style messages, I do not know if it makes sense to merge those changes into master.

Check style messages

---

CHANGELOG.md
src/main/java/edu/hm/hafner/analysis/parser/IdeaInspectionParser.java
src/test/java/edu/hm/hafner/analysis/parser/IdeaInspectionParserTest.java
src/test/resources/edu/hm/hafner/analysis/parser/issue56235.xml

and add more test cases for the IDEA inspection.
With the IntelliJ IIDEA I created a whole analysis of the actual code base and added some of those results to the test.

[JENKINS-55750] strip file:// from IDEA inspection file paths

---

CHANGELOG.md

Add changelog entries for recent changes in Pylint parser.

---

CHANGELOG.md
src/main/java/edu/hm/hafner/analysis/Issue.java
src/main/java/edu/hm/hafner/analysis/Report.java
src/test/java/edu/hm/hafner/analysis/IssueFilterTest.java

Use message **and** description for message filter.
Fixes https://issues.jenkins-ci.org/browse/JENKINS-56526

Fix for JENKINS-56526

---

src/main/java/edu/hm/hafner/analysis/parser/MentorParser.java
src/test/java/edu/hm/hafner/analysis/parser/MentorParserTest.java
src/test/resources/edu/hm/hafner/analysis/parser/modelsim.log

I also have a commit where I added code coverage reporting, as I didn't see a way to create the coverage report with the existing code.  If you want I can push that to this branch as well, or create another pull requests.

Add MentorGraphcis Modelsim/Questa log parser.

---

CHANGELOG.md
pom.xml
src/main/java/edu/hm/hafner/analysis/parser/DScannerParser.java
src/test/java/edu/hm/hafner/analysis/parser/DScannerParserTest.java
src/test/resources/edu/hm/hafner/analysis/parser/dscanner-incomplete-report.json
src/test/resources/edu/hm/hafner/analysis/parser/dscanner-report.json

Parser for DScanner (https://github.com/dlang-community/D-Scanner) added

DScanner parser added

---

src/main/java/edu/hm/hafner/analysis/Severity.java
src/main/java/edu/hm/hafner/analysis/parser/MentorParser.java
src/test/java/edu/hm/hafner/analysis/parser/MentorParserTest.java
src/test/resources/edu/hm/hafner/analysis/parser/modelsim.log

The current parser can't detect suppressible errors, but it should.

Add missing Modelsim error

---

src/main/java/edu/hm/hafner/analysis/parser/EclipseXMLParser.java

Category ID 180, PREVIEW_RELATED

Add new warning category from Eclipse compiler 3.20

---

Jenkinsfile
src/test/java/edu/hm/hafner/analysis/AbstractBenchmark.java
src/test/java/edu/hm/hafner/analysis/FingerprintGeneratorBenchmark.java
src/test/java/edu/hm/hafner/analysis/IssueDifferenceBenchmark.java
src/test/java/edu/hm/hafner/analysis/PackageNameResolverBenchmark.java
src/test/java/edu/hm/hafner/analysis/ReportSerializationBenchmark.java
src/test/java/edu/hm/hafner/analysis/parser/ParserBenchmark.java

See jenkinsci/warnings-ng-plugin#539 and jenkinsci/warnings-ng-plugin#525

Add parser benchmark test

---

pom.xml
src/main/java/edu/hm/hafner/analysis/parser/DockerLintParser.java
src/test/java/edu/hm/hafner/analysis/parser/DockerLintParserTest.java
src/test/resources/edu/hm/hafner/analysis/parser/dockerlint.json

Support for json format output of https://github.com/projectatomic/dockerfile_lint

Adding support for dockerlint json files

---

src/main/java/edu/hm/hafner/analysis/parser/BrakemanParser.java
src/test/java/edu/hm/hafner/analysis/parser/BrakemanParserTest.java
src/test/resources/edu/hm/hafner/analysis/parser/brakeman.json

Adds a parser for [Brakeman](https://brakemanscanner.org/) JSON reports.
Reference: https://github.com/jenkinsci/brakeman-plugin/pull/24#pullrequestreview-479474801

Add parser for Brakeman JSON reports

---

.github/dependabot.yml
pom.xml
src/main/java/edu/hm/hafner/analysis/parser/PyLintParser.java
src/test/java/edu/hm/hafner/analysis/parser/PylintParserTest.java
src/test/resources/edu/hm/hafner/analysis/parser/pylint-absolute-paths.txt

See [JENKINS-63948](https://issues.jenkins-ci.org/browse/JENKINS-63948) for details.

[JENKINS-63948] Support absolute paths on Windows for PyLint

---

src/main/java/edu/hm/hafner/analysis/Report.java

See [JENKINS-64070](https://issues.jenkins-ci.org/browse/JENKINS-64070).

[JENKINS-64070] FIX NPE if instance with old serialization is restored

---

src/main/java/edu/hm/hafner/analysis/IssueParser.java
src/main/java/edu/hm/hafner/analysis/Severity.java
src/main/java/edu/hm/hafner/analysis/parser/AntJavacParser.java
src/main/java/edu/hm/hafner/analysis/parser/Armcc5CompilerParser.java
src/main/java/edu/hm/hafner/analysis/parser/ArmccCompilerParser.java
src/main/java/edu/hm/hafner/analysis/parser/BrakemanParser.java
src/main/java/edu/hm/hafner/analysis/parser/BuckminsterParser.java
src/main/java/edu/hm/hafner/analysis/parser/CadenceIncisiveParser.java
src/main/java/edu/hm/hafner/analysis/parser/ClairParser.java
src/main/java/edu/hm/hafner/analysis/parser/DiabCParser.java
src/main/java/edu/hm/hafner/analysis/parser/ErlcParser.java
src/main/java/edu/hm/hafner/analysis/parser/GccParser.java
src/main/java/edu/hm/hafner/analysis/parser/GnatParser.java
src/main/java/edu/hm/hafner/analysis/parser/IarParser.java
src/main/java/edu/hm/hafner/analysis/parser/MetrowerksCwCompilerParser.java
src/main/java/edu/hm/hafner/analysis/parser/MetrowerksCwLinkerParser.java
src/main/java/edu/hm/hafner/analysis/parser/QacSourceCodeAnalyserParser.java
src/main/java/edu/hm/hafner/analysis/parser/SphinxBuildParser.java
src/main/java/edu/hm/hafner/analysis/parser/SunCParser.java
src/main/java/edu/hm/hafner/analysis/parser/pvsstudio/AnalyzerType.java
src/main/java/edu/hm/hafner/analysis/parser/pvsstudio/PlogMessage.java
src/test/java/edu/hm/hafner/analysis/IssueParserTest.java

See https://find-sec-bugs.github.io/bugs.htm#IMPROPER_UNICODE.

Fix case insensitive string comparison

---

src/main/java/edu/hm/hafner/analysis/IssueDifference.java

Avoid working with `null` references

---

src/test/java/edu/hm/hafner/analysis/parser/violations/CppCheckAdapterTest.java
src/test/resources/edu/hm/hafner/analysis/parser/violations/cpp-check-1.xml
src/test/resources/edu/hm/hafner/analysis/parser/violations/cpp-check-2.xml

See [JENKINS-61939](https://issues.jenkins-ci.org/browse/JENKINS-61939)

[JENKINS-61939] Try to expose CppCheckAdapter bug with a test case 

---

src/main/java/edu/hm/hafner/analysis/Issue.java
src/test/java/edu/hm/hafner/analysis/IssueTest.java
src/test/java/edu/hm/hafner/analysis/LineRangeListTest.java
src/test/java/edu/hm/hafner/analysis/ReportPrinterTest.java
src/test/java/edu/hm/hafner/analysis/ReportTest.java
src/test/java/edu/hm/hafner/analysis/SeverityTest.java

See https://jqno.nl/equalsverifier/

Use EqualsVerifier to test equals methods

---

src/main/java/edu/hm/hafner/analysis/registry/DoxygenDescriptor.java

How to call doxygen for parsing. 
Depending on https://issues.jenkins.io/browse/JENKINS-65547

add help to DoxygenDescriptor

---

src/main/java/edu/hm/hafner/analysis/LineRangeList.java
src/main/java/edu/hm/hafner/analysis/parser/CadenceIncisiveParser.java
src/test/java/edu/hm/hafner/analysis/parser/AntJavacParserTest.java
src/test/java/edu/hm/hafner/analysis/registry/ParsersTest.java

Code cleanup

---

SUPPORTED-FORMATS.md
src/main/java/edu/hm/hafner/analysis/parser/pvsstudio/AnalyzerType.java
src/main/java/edu/hm/hafner/analysis/parser/pvsstudio/PlogMessage.java
src/main/java/edu/hm/hafner/analysis/registry/PvsStudioDescriptor.java
src/test/java/edu/hm/hafner/analysis/parser/pvsstudio/PVSStudioParserTest.java

Migrating from viva64.com to pvs-studio.com
viva64.com => pvs-studio.com

Migrating from viva64.com to pvs-studio.com

---

src/main/java/edu/hm/hafner/analysis/registry/AquaScannerDescriptor.java

Adding an SVG icon for Aqua Scanner descriptor.
Also added URL for Aqua Scanner.

Adding SVG icon and URL for Aqua Scanner.

---

SUPPORTED-FORMATS.md
src/main/java/edu/hm/hafner/analysis/parser/PolyspaceParser.java
src/test/java/edu/hm/hafner/analysis/parser/PolyspaceParserTest.java

Simplify code of Polyspace parser

---

src/main/java/edu/hm/hafner/analysis/registry/PolyspaceDescriptor.java

Parser ID update to 'polyspace-parser'
Relevant pull request : https://github.com/jenkinsci/warnings-ng-plugin/pull/1412

Parser ID update to 'polyspace-parser'

---

SUPPORTED-FORMATS.md
src/main/java/edu/hm/hafner/analysis/parser/EmbeddedEngineerParser.java
src/main/java/edu/hm/hafner/analysis/registry/EmbeddedEngineerDescriptor.java
src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
src/test/java/edu/hm/hafner/analysis/parser/EmbeddedEngineerParserTest.java
src/test/resources/edu/hm/hafner/analysis/parser/ea.log

This pull request is to include a parser for .log  files generated from Embedded Engineer Code Generator tool.
Pull request for warnings-ng-plugin will be done after this request is approved.

Parser for Embedded Engineer Code Generator Tool

---

SUPPORTED-FORMATS.md
src/main/java/edu/hm/hafner/analysis/parser/CodeGeneratorParser.java
src/main/java/edu/hm/hafner/analysis/registry/CodeGeneratorDescriptor.java
src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
src/test/java/edu/hm/hafner/analysis/parser/CodeGeneratorParserTest.java
src/test/resources/edu/hm/hafner/analysis/parser/CodeGenerator.log

This pull request is to include a parser for .log files generated from Simulink Code Generator tool by Mathworks.
Pull request for warnings-ng-plugin will be done after this request is approved.

Parser for Simulink Code Generator tool

---

src/main/java/edu/hm/hafner/analysis/parser/EmbeddedEngineerParser.java
src/test/java/edu/hm/hafner/analysis/parser/EmbeddedEngineerParserTest.java
src/test/resources/edu/hm/hafner/analysis/parser/ea.log

There are enhancements done by the Embedded Engineer tool that produced a new format of the .log file being parsed. And also new type of Warning/Error was introduced. So The parser was edited accordingly. 
Relevant pull-request : https://github.com/jenkinsci/analysis-model/pull/879

[EmbeddedEnginee] Support native .log file format

---

pom.xml

Followup of https://github.com/uhafner/codingstyle/pull/826

Revert commons-io to 2.11.0

---

doc/dependency-graph.puml

Fix build scripts.

---

SUPPORTED-FORMATS.md
src/main/java/edu/hm/hafner/analysis/registry/AnsibleLintDescriptor.java
src/main/java/edu/hm/hafner/analysis/registry/BluePearlDescriptor.java
src/main/java/edu/hm/hafner/analysis/registry/CargoDescriptor.java
src/main/java/edu/hm/hafner/analysis/registry/CmakeDescriptor.java
src/main/java/edu/hm/hafner/analysis/registry/DoxygenDescriptor.java
src/main/java/edu/hm/hafner/analysis/registry/MavenConsoleDescriptor.java
src/main/java/edu/hm/hafner/analysis/registry/MsBuildDescriptor.java
src/main/java/edu/hm/hafner/analysis/registry/MyPyDescriptor.java
src/main/java/edu/hm/hafner/analysis/registry/PnpmAuditDescriptor.java

Updated logos and URLs in descriptors and ran the script to re-generate `SUPPORTED-FORMATS.md`
Generated markdown has a bunch of new URLs and a few new icons.
```[tasklist]
```

Updated logos and URLs in descriptors

---

.github/workflows/coverage.yml
.github/workflows/quality-monitor.yml
.github/workflows/update-badges.yml

Use the new [Quality Monitor](https://github.com/uhafner/quality-monitor/) to create badges and feedback in pull request.

Use new quality monitor action in workflows

---

SUPPORTED-FORMATS.md
src/main/java/edu/hm/hafner/analysis/parser/violations/BanditParserAdapter.java
src/main/java/edu/hm/hafner/analysis/registry/BanditDescriptor.java
src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
src/test/java/edu/hm/hafner/analysis/parser/violations/BanditAdapterTest.java
src/test/resources/edu/hm/hafner/analysis/parser/violations/bandit.txt

Add support for https://github.com/PyCQA/bandit.
Please see https://issues.jenkins.io/browse/JENKINS-70824 for details.

[JENKINS-70824] Add Bandit parser

---

SUPPORTED-FORMATS.md
src/main/java/edu/hm/hafner/analysis/IssueBuilder.java
src/main/java/edu/hm/hafner/analysis/LookaheadParser.java
src/test/java/edu/hm/hafner/analysis/parser/GccParserTest.java
src/test/resources/edu/hm/hafner/analysis/parser/issue70996.txt

See [JENKINS-70996](https://issues.jenkins.io/browse/JENKINS-70996) for details.

[JENKINS-70996] Ignore directory messages from other tools

---

src/main/java/edu/hm/hafner/analysis/Issue.java
src/main/java/edu/hm/hafner/analysis/IssueBuilder.java
src/main/java/edu/hm/hafner/analysis/Report.java
src/test/java/edu/hm/hafner/analysis/IssueTest.java
src/test/java/edu/hm/hafner/analysis/ReportTest.java

[Remove partOfModifiedCode flag from equals.](https://github.com/jenkinsci/analysis-model/commit/e6922eaef588e85816453f016fe2cfc216c04815) and [Add method to obtain the issues that are part of modified code.](https://github.com/jenkinsci/analysis-model/commit/df9202177f05449e47319de07e20b25f8e15433f).

Part of modified code not equals

---

src/main/java/edu/hm/hafner/analysis/registry/PmdDescriptor.java

See https://github.com/pmd/pmd/pull/4970

Use the new square SVG image for PMD results

---

.github/workflows/quality-monitor.yml

Add ErrorProne to quality monitor

---

src/main/java/edu/hm/hafner/analysis/FullTextFingerprint.java
src/test/java/edu/hm/hafner/analysis/FingerprintGeneratorTest.java
src/test/java/edu/hm/hafner/analysis/FullTextFingerprintTest.java

Made context lines configurable in the fingerprinting process. See : https://issues.jenkins.io/browse/JENKINS-61607.
(Draft: Currently used for creating an artifact)

Added methods to configure context lines in FullTextFingerprint

---

pom.xml
src/main/java/edu/hm/hafner/analysis/parser/Armcc52CompilerParser.java
src/main/java/edu/hm/hafner/analysis/parser/ArmccAbstractParser.java
src/main/java/edu/hm/hafner/analysis/parser/ArmccCompilerParser.java
src/main/java/edu/hm/hafner/analysis/registry/ArmccCompilerDescriptor.java
src/test/java/edu/hm/hafner/analysis/parser/Armcc52CompilerParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/Armcc5CompilerParserTest.java
src/test/java/edu/hm/hafner/analysis/parser/ArmccCompilerParserTest.java

Since we already have a parser aggregation it makes sense to reuse it.

Refactor Armcc parsers

---

src/main/java/edu/hm/hafner/analysis/MsBuildPattern.java
src/main/java/edu/hm/hafner/analysis/parser/MsBuildParser.java
src/test/java/edu/hm/hafner/analysis/parser/MsBuildParserTest.java
src/test/resources/edu/hm/hafner/analysis/parser/issue67291.txt

FIXES - [67291](https://issues.jenkins.io/browse/JENKINS-67291)
Refactored the MsBuildParser's Pattern in a simplified manner for better code readability and maintainability.
Added the mentioned combinations of line and col to the pattern.
Added Tests for each combination.

[JENKINS-67291] Parse MSBuild-compatible diagnostic with (line,col,line,col)

---

.github/quality-gates.json
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/update-badges.yml
pom.xml
src/main/java/edu/hm/hafner/analysis/Report.java
src/main/java/edu/hm/hafner/analysis/parser/CargoClippyParser.java
src/main/java/edu/hm/hafner/analysis/parser/FxCopParser.java
src/main/java/edu/hm/hafner/analysis/parser/RfLintParser.java
src/main/java/edu/hm/hafner/analysis/parser/YuiCompressorParser.java

Bump the version of maven from 3.3.9 to 3.3.11

---

src/main/java/edu/hm/hafner/analysis/Severity.java
src/main/java/edu/hm/hafner/analysis/parser/NpmAuditParser.java
src/main/java/edu/hm/hafner/analysis/registry/NpmAuditDescriptor.java
src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java
src/test/java/edu/hm/hafner/analysis/SeverityTest.java
src/test/java/edu/hm/hafner/analysis/parser/NpmAuditParserTest.java
src/test/java/edu/hm/hafner/analysis/registry/ParserRegistryTest.java
src/test/resources/edu/hm/hafner/analysis/parser/npm-audit.json

This PR adds a new parser for the json report of `npm audit`.
Tested with a report of a test npm project. Used as base also for the unit tests.

Add parser for npm audit reports
