src/test/java/edu/hm/hafner/analysis/parser/GhsMultiParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/GnatParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/GnuFortranParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/GnuMakeGccParserTest.java
Refactor  GhsMultiParserTest, GnatParserTest, GnuFortranParserTest and GnuMakeGccParserTest to use custom assertions instead of the JUnit assertions.
=> Refactor parser tests to use assertj

src/test/java/edu/hm/hafner/analysis/parser/MsBuildParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/NagFortranParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/P4ParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/Pep8ParserTest.java
Changes for **MsBuildParserTest**, **NagFortranParserTest**, **P4ParserTest** & **Pep8ParserTest**:
- Now implement AbstractParserTest and necessary methods
- Code cleanup where it made sense
- Changed test-cases to use junit5 (removed public modifier from methods)
=> Parser tests now implement AbstractParserTest

src/main/java/edu/hm/hafner/analysis/parser/dry/cpd/CpdParser.java, src/test/java/edu/hm/hafner/analysis/parser/dry/cpd/CpdParserTest.java
The endline was not calculated the right way, which lead to displaying in the wrong number of duplicate lines in the frontend.
=> fixed the endLineNumber for Cpd-Warnings

src/main/java/edu/hm/hafner/analysis/parser/EclipseParser.java, src/test/java/edu/hm/hafner/analysis/parser/EclipseParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/eclipse-columns.txt, src/test/resources/edu/hm/hafner/analysis/parser/eclipse-withinfo.txt, src/test/resources/edu/hm/hafner/analysis/parser/issue21377.txt
* Support for 'INFO' at priority WARNING_LOW
* 'ERROR' is now at priority ERROR
* Note for how markers are counted (different from XML output)
* Skip leading type marker for log-in-log situations
* Allow source code to be one or more lines long
* Account for leading tab in column pointer line
* Correct error in test input of JENKINS-21377
=> Updates to Eclipse Compiler output parsing

src/main/java/edu/hm/hafner/analysis/parser/IntelParser.java, src/test/java/edu/hm/hafner/analysis/parser/IntelParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/intelc.txt
Add a group to the regular expression to  check for the pattern '\d+>' at the beginning of the line. The line starts with a "project number" followed by '>' when using the Intel Compiler through Visual Studio.
A new test is added to test it.
=> IntelParser: Check for project number in regex

src/main/java/edu/hm/hafner/analysis/parser/MsBuildParser.java, src/test/java/edu/hm/hafner/analysis/parser/MsBuildParserTest.java
By setting the filename to MSBUILD in cases when
no fielname is specified within the message, follow-up
plugins will try to search for a non-existing file,
yielding to unnecessary error messages.
=> Fix for JENKINS-55373

CONTRIBUTING.md, src/main/java/edu/hm/hafner/analysis/Report.java, src/test/java/edu/hm/hafner/analysis/IssueFilterTest.java
This is the first part of the implementation. Only after release of the
plugin we will be able to continue the implementation in the
warnings-ng-plugin code.
Also fix a typo in the contributing guideline, while we are at it.
=> JENKINS-55442: add a filter by issue message

src/main/java/edu/hm/hafner/analysis/parser/AnsibleLintParser.java, src/test/java/edu/hm/hafner/analysis/parser/AnsibleLintParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/ansibleLint.txt
According to [the Ansible list of rules](https://docs.ansible.com/ansible-lint/rules/default_rules.html), the rule category is not prefixed with `ANSIBLE` anymore but instead with an `E`. This is covered by what I get as output of Ansible Lint 4.0.1:
```
+ /usr/bin/env bash -c set -eo pipefail; ansible-lint -p site.yml | tee output-lint.txt
/home/rancher/jenkins/workspace/rga_ansible-office_PR-19/roles/jenkins_slave/tasks/create_jenkins_user.yml:9: [E301] Commands should not change things if nothing needs doing
/home/rancher/jenkins/workspace/rga_ansible-office_PR-19/roles/jenkins_slave/tasks/install_java.yml:1: [E301] Commands should not change things if nothing needs doing
/home/rancher/jenkins/workspace/rga_ansible-office_PR-19/roles/jenkins_slave/tasks/update_software.yml:2: [E301] …
```
=> Fix parsing Ansible Lint output

src/main/java/edu/hm/hafner/analysis/parser/CppLintParser.java, src/test/java/edu/hm/hafner/analysis/parser/CppLintParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/cpplint-message-with-colon.txt
Require the line number to be at least one digit by changing from "*" to "+". This will prevent the parser from treating the C++ scope resolution operator (::) as the separator between the filename, line number and message.
As shown in the test I had problem with the following message:
`/path/to/file.cpp:1: Is this a non-const reference? If so, make const or use a pointer: std::vector<int> & indices  [runtime/references] [2]`
where the filename would be set to `/path/to/file.cpp:1: Is this a non-const reference? If so, make const or use a pointer: std`, the line number an empty string and the message just `vector<int> & indices`
I am not sure I put the test in the correct place. Please advise me if you have any other suggestions.
=> CppLint message with colon

src/main/java/edu/hm/hafner/analysis/parser/IarParser.java, src/test/java/edu/hm/hafner/analysis/parser/IarParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/issue8823.txt
Older versions of IAR for ARM (We currently use 7.20.2) report warnings in a different format.
e.g.
"d:\jenkins\workspace\Nightly\src\flash\flashdrv.c",861 Warning[Pe177]: function "FlashErase" was declared but never referenced
These could be identified by the parser prior to commit c234b94.
I've tweaked the regex to restore functionality with these older versions, without breaking the current matching behaviour.
Please consider for a merge into master.
=> Regex tweak to restore support for older versions of IAR for ARM

src/main/java/edu/hm/hafner/analysis/parser/IntelParser.java, src/test/java/edu/hm/hafner/analysis/parser/IntelParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/intelc.txt
Look for diagnostics with the category "message" (in addition to remark,
warning and error). At the highest warning levels the Intel compiler
outputs these "warnings" which should be parsed as well.
A test is added to show it is working.
=> IntelParser: Look for "message" as well

src/main/java/edu/hm/hafner/analysis/parser/IarCstatParser.java, src/test/java/edu/hm/hafner/analysis/parser/IarCstatParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/iar-cstat.txt
try to add support for the IAR CSTAT tool
=> add support for the IAR CSTAT tool

src/main/java/edu/hm/hafner/analysis/parser/PyLintParser.java, src/test/java/edu/hm/hafner/analysis/parser/PylintParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/pyLint.txt
Add support for package and module in Pylint.
In python, a project can look like:
```
src
└── package
├── __init__.py
├── sub_package1
│   ├── __init__.py
│   ├── module1.py
│   └── module2.py
└── sub_package2
├── __init__.py
├── module3.py
└── module4.py
```
So if a file named `__init__.py` exists in a folder, python will consider that folder as a package (or sub-package, but it's the same as a package, so no big difference). And any file that ends in `.py` is called a module.
Since warnings-ng supports package and module, I decided to also add support for them in the pylint parser.
=> Add support for package and module in Pylint

src/main/java/edu/hm/hafner/analysis/parser/PyLintParser.java, src/test/java/edu/hm/hafner/analysis/parser/PylintParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/pyLint.txt, src/test/resources/edu/hm/hafner/analysis/parser/pylint_parseable.txt
As mentionned in [Jira](https://issues.jenkins-ci.org/browse/JENKINS-44915?focusedCommentId=303793&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-303793), the actual categories for Pylint should be types.
So I took the time to do the change. So I swapped the categories for the types, and introduced real categories. Now the Pylint parser does the same thing as the other parsers.
Note that I also added the category `[I]nformational` since it was missing and it's a valid Pylint category.
=> Pylint: Add types and make categories types and categories, categories

CHANGELOG.md, src/main/java/edu/hm/hafner/analysis/parser/JavaDocParser.java, src/test/java/edu/hm/hafner/analysis/parser/JavaDocParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/issue54506.txt
when there is a whitespace before the @ sign then it shall be indicated as interesing line for the JavaDoc parser, with this I was able to reduce the false positive.
Check also some issue7718 cases.
=> [JENKINS-54506] fixed Some compiler warnings are misidentified as Javadoc warnings

CHANGELOG.md, src/main/java/edu/hm/hafner/analysis/parser/MsBuildParser.java, src/test/java/edu/hm/hafner/analysis/parser/MsBuildParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/issue42823.txt
probably it is better to generate the wrong string instead of store it in the file. What do you think?
=> Jenkins 42823: False positive with msbuild parser

CHANGELOG.md, src/main/java/edu/hm/hafner/analysis/Report.java, src/test/java/edu/hm/hafner/analysis/IssueFilterTest.java
All issue filters use a regular expression to match the content of an issue property. Currently the filter pattern must match the whole string property. This is somewhat cumbersome and not obvious to users. So this PR changes this behavior: now `Pattern.find` is used to find the next match in a substring of the property (Previously, `Pattern.matches` has been used).
=> Use find rather than match in regexp filters

pom.xml, src/main/java/edu/hm/hafner/analysis/parser/CMakeParser.java, src/test/java/edu/hm/hafner/analysis/parser/CMakeParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/cmake.txt
I didn't find a parser that can parse warnings from [CMake](https://cmake.org/). So I took a shot at it.
=> CMake warnings support

src/main/java/edu/hm/hafner/analysis/parser/checkstyle/CheckStyleParser.java, src/test/java/edu/hm/hafner/analysis/parser/CheckStyleParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/checkstyle/all-severites.xml
Fixed PHP CodeSniffer errors treated as warnings:
Changed severity mapping of CheckStyleParser
=> Jenkins 56214

CHANGELOG.md, src/main/java/edu/hm/hafner/analysis/parser/MsBuildParser.java, src/test/java/edu/hm/hafner/analysis/parser/MsBuildParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/issue48647.txt
https://issues.jenkins-ci.org/browse/JENKINS-48647
when log lines start with a prefix, e.g. "17:4>", it will be removed by regular expression.
=> add Test and fix to Issue 48647

CHANGELOG.md, pom.xml, src/main/java/edu/hm/hafner/analysis/FileReaderFactory.java, src/test/java/edu/hm/hafner/analysis/FileReaderFactoryTest.java, src/test/resources/edu/hm/hafner/analysis/encoded-with-ISO8859-1.xml, src/test/resources/edu/hm/hafner/analysis/encoded-with-UTF8.xml, src/test/resources/edu/hm/hafner/analysis/encoded-without-encoding.xml
Detect charset to use from xml header, when not specified in the FileReaderFactory constructor. Added a FileReaderFactory constructor without a charset parameter.
=> JENKINS-52477 - XML Parsers should use report encoding given in XML file

CHANGELOG.md, pom.xml, src/main/java/edu/hm/hafner/analysis/parser/SonarQubeDiffParser.java, src/main/java/edu/hm/hafner/analysis/parser/SonarQubeIssuesParser.java, src/main/java/edu/hm/hafner/analysis/parser/SonarQubeParser.java, src/test/java/edu/hm/hafner/analysis/parser/SonarQubeIssuesParserTest.java
Fixed: https://issues.jenkins-ci.org/browse/JENKINS-52462
- Added parseEnd method and use textRange.
- Changed parseStart to abstract and implemented in both parsers.
- Fixed tests
- Increased version number and added info to changelog
=> Jenkins 52462: SonarQubeParser should read textRange

src/main/java/edu/hm/hafner/analysis/parser/JavacParser.java, src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/javac-timestamps.txt
On jenkins 2.165 with timestamper plugin 1.9, a declarative
pipeline as:
pipeline {
options {
timestamps()
}
stages {
// ... maven build
}
}
generates log lines with two whitespaces after the timestamps.
This change allows arbitrary whitespace; additionally it tidies
up the string concatenation of the regex.
See: https://www.regexplanet.com/share/index.html?share=yyyydxkgm6r
=> Allow arbitrary w/s between timestamp and maven log line

CHANGELOG.md, src/main/java/edu/hm/hafner/analysis/parser/MsBuildParser.java, src/test/java/edu/hm/hafner/analysis/parser/MsBuildParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/issue57365.txt
Fixes false positives for MsBuild if e.g. a build project name contains the string info/note/warning.
This change requires a whitespace in front of the strings note, info, warning or fatal error to be recognized as the corresponding warnings.
See also: https://issues.jenkins-ci.org/browse/JENKINS-57365
=> [JENKINS-57365] Fixes false positives for MsBuild

src/main/java/edu/hm/hafner/analysis/Issue.java, src/main/java/edu/hm/hafner/analysis/parser/JsonParser.java, src/main/java/edu/hm/hafner/analysis/parser/XmlParser.java, src/test/java/edu/hm/hafner/analysis/parser/JsonParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/json-issues.log
https://issues.jenkins-ci.org/browse/JENKINS-57098
=> [JENKINS-57098] Add JSON Parser

src/main/java/edu/hm/hafner/analysis/parser/JsonBaseParser.java, src/main/java/edu/hm/hafner/analysis/parser/JsonLogParser.java, src/main/java/edu/hm/hafner/analysis/parser/JsonParser.java, src/test/java/edu/hm/hafner/analysis/parser/JsonLogParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/JsonParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/issues-broken.json, src/test/resources/edu/hm/hafner/analysis/parser/issues-invalid.json, src/test/resources/edu/hm/hafner/analysis/parser/issues-no-issues.json, src/test/resources/edu/hm/hafner/analysis/parser/issues.json, src/test/resources/edu/hm/hafner/analysis/parser/json-issues-empty.txt, src/test/resources/edu/hm/hafner/analysis/parser/json-issues.log
As discussed in https://github.com/jenkinsci/analysis-model/pull/168#issuecomment-494269551 and the next comments, this PR organize JSON parser differently:
**1.** `JsonLogParser` (introduced as `JsonParser` in #168)
The format is a file (not `.xml` and not `.json`) where each line is an issue serialized as separated JSON object.
**2.** `JsonParser`
Parse a JSON report produced by the "[Jenkins Warnings Next Generation Plugin](https://github.com/jenkinsci/warnings-ng-plugin)" with the API call: `GET [build-url]/[tool-id]/all/api/json`
The format is json file (ending with `.json`) containing a valid JSON Object.
This object as a member `issues` containing an array of issues. Example:
```json
{
"issues": [
{"fileName": "file.txt", "lineStart": 5, "lineEnd": 5, "message": "Message 1"}, …
```
=> [JENKINS-57098] JSON Parser for Json report

src/main/java/edu/hm/hafner/analysis/parser/MavenConsoleParser.java, src/test/java/edu/hm/hafner/analysis/parser/MavenConsoleParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/maven-multimodule.log
This is a hacktoberfest contribution.
See [JENKINS-59440](https://issues.jenkins-ci.org/browse/JENKINS-59440).
The maven parser uses and displays the module in which the issue occured.
=> [JENKINS-59440] Add support for multi-module maven builds

pom.xml, src/main/java/edu/hm/hafner/analysis/parser/JavacParser.java, src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/javac-errorprone.txt
This is a hacktoberfest contribution.
See [JENKINS-57428](https://issues.jenkins-ci.org/browse/JENKINS-57428).
The JavacParser was changed to no longer include errorprone warnings.
=> [JENKINS-57428] Ignore errorprone warnings in the javac-parser

src/main/java/edu/hm/hafner/util/PathUtil.java, src/test/java/edu/hm/hafner/analysis/parser/CppLintParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/FxcopParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/GendarmeParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/IarParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/MsBuildParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/TiCcsParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/dry/simian/SimianParserTest.java, src/test/java/edu/hm/hafner/util/PathUtilTest.java
Inside of `AffectedFilesResolver.isInWorkspace()` of the warnings-ng project, the check fails in cases where different sources of file names may have upper case drive letters or lower case ones, on Windows.  This normalizes paths to force the drive letter into caps.
[AffectedFilesResolver.java](https://github.com/jenkinsci/warnings-ng-plugin/blob/master/src/main/java/io/jenkins/plugins/analysis/core/util/AffectedFilesResolver.java)
=> Normalize Windows drive letters to upper case.

src/main/java/edu/hm/hafner/analysis/parser/SbtScalacParser.java, src/test/resources/edu/hm/hafner/analysis/parser/sbtScalac.txt
This is the refinement of a previous pull request without the binary files. 
Resolved issue where [error] Total time: 127 s, completed Oct 7, 2019 9:11:30 AM was noted as an error when parsing the output of SBT parser.
- added '[error] Total time: 127 s, completed Oct 7, 2019 9:11:30 AM' to test file for SbtScalacParserTest.java
- changed regex to "^(\\[warn\\]|\\[error\\](?!\\s+Total\\stime:))\\s*(.*?):(\\d+)(?::\\d+)?:\\s*(.*)$" to add negative lookahead prevening it from picking up '[error] Total time:' identifier
=> [JENKINS-59865] Skip lines that contain total time summary

pom.xml, src/main/java/edu/hm/hafner/analysis/Report.java, src/test/java/edu/hm/hafner/analysis/ReportTest.java
Each report should have a map of origin IDs to human readable names.
Required for https://github.com/jenkinsci/warnings-ng-plugin/pull/207
=> [JENKINS-57638] Add configurable report names

src/main/java/edu/hm/hafner/analysis/Issue.java
Since release 8.0.0 `description` is of type `String`. Jenkins sets this field to `null` in some cases.
=> [JENKINS-61293] Restore description to `UNDEFINED` if unmarshalled is `null`

src/main/java/edu/hm/hafner/analysis/parser/TaskingVxCompilerParser.java
Make TASKING_VX_COMPILER_WARNING_PATTERN more strict to reduce the possibility of matching messages output from other tools.
=> Strengthen TaskingVx warning pattern

src/main/java/edu/hm/hafner/analysis/parser/GhsMultiParser.java, src/test/java/edu/hm/hafner/analysis/parser/GhsMultiParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/ghsmulti.txt
On GHS Multi 201914_2fp we get some output logs with the following format : 
> "D:/workspace/TEST/mytest.c", line 639 (col. 10): warning #11-D: unrecognized preprocessing directive
Due to this new column output, warnings are no more matched by parser.
=> Add new log format for GHSMulti compiler

src/main/java/edu/hm/hafner/analysis/parser/FlawfinderParser.java, src/test/java/edu/hm/hafner/analysis/parser/FlawfinderParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/flawfinder.log
This change adds a Flawfinder parser which is a static analysis tool for finding potential security flaws in C/C++.  Project can be found here: https://github.com/david-a-wheeler/flawfinder
=> Add Flawfinder Parser

src/main/java/edu/hm/hafner/analysis/parser/RuboCopParser.java
Just a bit of clean up. Was basing the flawfinder parser on this parser so I took the advice offered in that pull and applied it here.
=> Convert RuboCop Parser to use named groups

src/main/java/edu/hm/hafner/analysis/parser/AntJavacParser.java, src/test/java/edu/hm/hafner/analysis/parser/AntJavacParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/issue63346.txt
Warnings with an `@` symbol are JavaDoc warnings and should be parsed by the JavaDoc parser.
A simple quick fix for https://issues.jenkins-ci.org/browse/JENKINS-63346. Should be improved if this fix skips other warnings that are related to annotations.
=> [AntJavaParser] Ignore warnings that contain a `@` symbol

src/test/java/edu/hm/hafner/analysis/parser/violations/JUnitAdapterTest.java, src/test/resources/edu/hm/hafner/analysis/parser/violations/report.junit
```
edu.hm.hafner.analysis.ParsingException: Exception occurred during parsing
NoSuchElementException: No value present
java.util.NoSuchElementException: No value present
at java.util.Optional.get(Optional.java:135)
at se.bjurr.violations.lib.parsers.JUnitParser.parseReportOutput(JUnitParser.java:36)
at edu.hm.hafner.analysis.parser.violations.AbstractViolationAdapter.parse(AbstractViolationAdapter.java:35)
at edu.hm.hafner.analysis.AbstractParserTest.parse(AbstractParserTest.java:106)
at edu.hm.hafner.analysis.parser.violations.JUnitAdapterTest.shouldParseIosReport(JUnitAdapterTest.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at …
```
=> [JENKINS-63527] Create a test case that exposes the bug

src/main/java/edu/hm/hafner/analysis/parser/JavacParser.java, src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/kotlin-gradle-error.txt
This adds support for parsing Kotlin errors like
```
e: /project/app/src/main/java/ui/Activity.kt: (214, 35): Unresolved reference: feth
```
Previously, only Kotlin warnings would be parsed. However, with the Jenkins Warnings NG plugin being able to push warnings/errors to GitHub as GitHub Checks, having Kotlin errors directly in GitHub would be a nice addition 🙂.
=> Add support for parsing Kotlin errors

src/main/java/edu/hm/hafner/analysis/parser/FoodcriticParser.java, src/test/java/edu/hm/hafner/analysis/parser/FoodcriticParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/foodcritic.log
This change adds a parser for [Foodcritic](http://www.foodcritic.io), a linting tool for [Chef](https://www.chef.io/) cookbooks.
=> Add Foodcritic parser for linting Chef cookbooks.

src/main/java/edu/hm/hafner/analysis/parser/violations/JUnitAdapter.java
Just wrapping the readStream with a try-with-resources to autoclose the stream after use, similar to e.g. JsonLogParser.
=> [JENKINS-64155] Close stream in JunitAdapter

src/main/java/edu/hm/hafner/analysis/parser/checkstyle/CheckStyleParser.java, src/test/java/edu/hm/hafner/analysis/parser/CheckStyleParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/checkstyle/issue60859.xml
The CheckStyle parser does not work correctly for reports generated by other tools. E.g., hadolint reports the type of a warning using a simple string. This type is not correctly detected, see [JENKINS-60859](https://issues.jenkins-ci.org/browse/JENKINS-60859).
This PR simplifies the type detection: if the type is not in the native CheckStyle format (that contains a dot) then the whole
type will be returned.
=> [JENKINS-60859] Improve type detection for CheckStyle variants

pom.xml, src/test/java/edu/hm/hafner/analysis/parser/violations/CppCheckAdapterTest.java, src/test/resources/edu/hm/hafner/analysis/parser/violations/issue64519.xml
Exposes [JENKINS-55733](https://issues.jenkins-ci.org/browse/JENKINS-55733)
=> [JENKINS-55733] - CppCheck parser ignores errors without location.

src/main/java/edu/hm/hafner/analysis/parser/NagFortranParser.java, src/test/java/edu/hm/hafner/analysis/parser/NagFortranParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/NagFortran.txt, src/test/resources/edu/hm/hafner/analysis/parser/NagFortranExtensionF2008.txt, src/test/resources/edu/hm/hafner/analysis/parser/NagFortranExtensionF2018.txt, src/test/resources/edu/hm/hafner/analysis/parser/NagFortranExtensionNAG.txt, src/test/resources/edu/hm/hafner/analysis/parser/NagFortranNonStandardObsolete.txt
Remove assertions on unset properties. This is already checked in the `IssueBuilder` tests.
Followup on #552
=> Simplify NAG fortran parser tests

src/main/java/edu/hm/hafner/analysis/IssueDifference.java
Currently the difference of reports use a quadratic algorithm take takes hours when issues are several thousands.
The changes done copes with that.
=> Improve runtime of delta computation

src/main/java/edu/hm/hafner/analysis/parser/RuboCopParser.java, src/test/java/edu/hm/hafner/analysis/parser/RuboCopParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/rubocop.log
RuboCop 1.6.0 introduced the "[Correctable]" notation in it's standard output (https://github.com/rubocop-hq/rubocop/pull/9187).
As a result of this change, the parser now doesn't recognize these lines as issues anymore, but only lists non-correctable issues.
This PR fixes this direct problem.
The discussion on the issue linked above mentioned, that the "progress" format is not meant to be stable for machine parsing. It might be a good idea to switch to the XML/JSON formatters in the long run...
=> RuboCop Parser: Parse lines with '[Correctable]' addition

src/main/java/edu/hm/hafner/analysis/parser/IarParser.java, src/test/java/edu/hm/hafner/analysis/parser/IarParserTest.java
Errors and fatal errors should be an Severity.ERROR, not Severity.Warning (even high) - code lead to mistakes by setting qaulity gates on unexistgin level i.e. "TOTAL_ERROR" in pipeline script.
=> IarParser - Map errors and fatal errors to severity ERROR

src/main/java/edu/hm/hafner/analysis/Report.java, src/test/java/edu/hm/hafner/analysis/ReportTest.java
When copying the properties of a report the messages of the whole report tree must be copied into the new report.
=> Add missing info messages of sub reports

pom.xml, src/main/java/edu/hm/hafner/analysis/Report.java, src/test/java/edu/hm/hafner/analysis/ReportTest.java
When the ID is set for a report aggregation the ID and name should be pushed down the hierarchy.
=> Copy origin ID and name recursively for sub-reports

pom.xml, src/main/java/edu/hm/hafner/analysis/Report.java, src/test/java/edu/hm/hafner/analysis/ReportTest.java
When a report is copied with `addAll` then the warning messages should be copies as well for the whole added structure.
=> Copy messages recursively for sub-reports and their childs.

src/main/java/edu/hm/hafner/analysis/parser/SphinxBuildParser.java, src/test/java/edu/hm/hafner/analysis/parser/SphinxBuildParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/issue63216.txt
Add tests to `SphinxBuildParserTest.java`  and modify warning-pattern in `SphinxBuildParser.java`
=> [JENKINS-63216] Sphinx parser misses warnings without line number

SUPPORTED-FORMATS.md, src/main/java/edu/hm/hafner/analysis/parser/CppLintParser.java, src/main/java/edu/hm/hafner/analysis/registry/CppLintDescriptor.java
Switch all occurrences of "C++ Lint" to Cpplint.
In the documentation, the tool is only mentioned by the name cpplint.
Source:
https://github.com/google/styleguide/tree/gh-pages/cpplint
https://pypi.org/project/cpplint
It solves (works around) issue [JENKINS-67101](https://issues.jenkins.io/browse/JENKINS-67101)
=> Rename "C++ Lint" to Cpplint

src/main/java/edu/hm/hafner/analysis/parser/TrivyParser.java, src/test/java/edu/hm/hafner/analysis/parser/TrivyParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/issue67296.json
See [JENKINS-67296](https://issues.jenkins.io/browse/JENKINS-67296).
=> [JENKINS-67245] Do not escape tool names anymore

src/main/java/edu/hm/hafner/analysis/parser/MsBuildParser.java, src/test/java/edu/hm/hafner/analysis/parser/MsBuildParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/issue56613.txt
Fixed [55613](https://issues.jenkins.io/browse/JENKINS-56613): MSBuildParser is able to handle tool messages.
Added new test file.
Fixed tests.
=> [JENKINS-56613] Ignore warnings with a tool as source (e.g., exe files)

src/main/java/edu/hm/hafner/analysis/parser/TaskingVxCompilerParser.java, src/test/java/edu/hm/hafner/analysis/parser/TaskingVxCompilerParserTest.java, src/test/java/edu/hm/hafner/analysis/registry/ParsersTest.java, src/test/resources/edu/hm/hafner/analysis/parser/tasking-vx.txt
Updating regexp pattern for Tasking VX Toolset to include C166 compiler (e. g. Infineon XC2000) which start with
c166 (I|W|E|F):
Detection broke with commit 79f4bcf, which switched from any character to a-z.
Test with regex101.com and console outputs from c166 compiler. 
Example:
c166 E272: ["../IoDriver/src/IO_BRBL.c" 79/33] undeclared identifier "BL_AUTH_SEED"
Detection works as expected.
=> Updating regexp pattern for Tasking VX Toolset C166

src/main/java/edu/hm/hafner/analysis/parser/GhsMultiParser.java, src/test/java/edu/hm/hafner/analysis/parser/GhsMultiParserTest.java, src/test/java/edu/hm/hafner/analysis/registry/ParsersTest.java, src/test/resources/edu/hm/hafner/analysis/parser/ghsmulti.txt
When a log issue has a column set, there is no cursor ('^') at the end of the message.
The current behavior was to set the end of the message issue when a line had only spaces and the char ^ (MESSAGE_END_REGEX)
Therefore, when a message issue like below append, it took has a message everything until the end of the next log issue 
`"D:/workspace/TEST/mytest.c", line 639 (col. 10): warning #11-D: unrecognized preprocessing directive`
GhsMultiParserTest were green only because this specific message used has an example was at the end of the message
Solution : 
- Only extract the rest of the message if there is no column set
- And move the specific message above in the ghsmulti.txt with the test (GhsMultiParserTest) modifications due to this log movement
For the moment all logs containing a …
=> Fix GhsMultiParser log issue without cursor

src/main/java/edu/hm/hafner/analysis/parser/ClangTidyParser.java, src/test/java/edu/hm/hafner/analysis/parser/ClangTidyParserTest.java, src/test/java/edu/hm/hafner/analysis/registry/ParsersTest.java, src/test/resources/edu/hm/hafner/analysis/parser/ClangTidy.txt
Current implementation fails to parse a path which contains white
spaces. Jenkins UI fails to link a file position.
There were many edge cases dealt already. So I have no choice but to make a workaround.
=> clang-tidy: Allow white spaces in a path

src/main/java/edu/hm/hafner/analysis/parser/AnsibleLintParser.java, src/test/java/edu/hm/hafner/analysis/parser/AnsibleLintParserTest.java, src/test/java/edu/hm/hafner/analysis/registry/ParsersTest.java, src/test/resources/edu/hm/hafner/analysis/parser/ansibleLint.txt
Hi, 
this pull request adds support for the new ansible-lint (version >= 6.1.0) PEP8 warning format. Further details can be found in https://issues.jenkins.io/browse/JENKINS-68740.
- Edited regex to support additional colon in warning
- Colon is marked as optional (older ansible-lint version (<6.1.0) does not have this colon)
=> JENKINS-68740: Support ansible-lint >=6.1.0 warning format

src/main/java/edu/hm/hafner/analysis/parser/TrivyParser.java
I noticed that Trivy parser had the following issues with its `formatDescription` function:
- Unclosed `<p>` tag
- `<b>File</b>:` vs `<b>File :</b>`
- Unescaped characters
Based on the above, I have changed 'formatDescription' to use j2html.
```html
<p>
<div><b>File</b>: bind-export-libs</div>
<div><b>Installed Version:</b> 32:9.11.13-6.el8_2.1</div>
<div><b>Fixed Version:</b> 32:9.11.20-5.el8</div>
<div><b>Severity:</b> MEDIUM</div><p>In ISC BIND9 versions BIND 9.11.14 -> 9.11.19, BIND 9.14.9 -> 9.14.12, BIND 9.16.0
-> 9.16.3, BIND Supported Preview Edition 9.11.14-S1 -> 9.11.19-S1: Unless a nameserver is providing authoritative
service for one or more zones and at least one zone contains an empty non-terminal entry containing an asterisk
("*") character, this defect cannot be …
```
=> Fixing Trivy descriptions.

src/main/java/edu/hm/hafner/analysis/LookaheadParser.java, src/test/java/edu/hm/hafner/analysis/parser/Gcc4CompilerParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/issue69242.txt
- [ x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ x] Ensure that the pull request title represents the desired changelog entry
- [x ] Please describe what you did
- [x ] Link to relevant issues in GitHub or Jira
- [x ] Link to relevant pull requests, esp. upstream and downstream changes
- [x ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
Jira Issue :- [Issue 69242](https://issues.jenkins.io/browse/JENKINS-69242)
Currently regex detect directory path which starts and end with ' or `, so existing ENTERING_DIRECTORY_PATH regex was ignoring the path eg:- 
Entering directory /tmp/testDir806422480360626789 
Leaving directory /tmp/testDir806422480360626789
and accepting these:-
Entering …
=> [JENKINS-69242] Improve path detection during subdirectory traversal

src/main/java/edu/hm/hafner/analysis/parser/RevApiParser.java
Revapi severity "EQUIVALENT" which is no error got mapped to "WARNING_NORMAL" and not "WARNING_LOW"
=> Map RevApi Severity of `EQUIVALENT` to `WARNING_LOW`

src/main/java/edu/hm/hafner/analysis/parser/ErrorProneParser.java, src/test/java/edu/hm/hafner/analysis/parser/ErrorProneParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/maven-error-prone.log
Currently the parser ignores those warnings.
=> Improve ErrorProne regexp to catch also warnings without column numbers

src/main/java/edu/hm/hafner/analysis/parser/AnsibleLintParser.java, src/test/java/edu/hm/hafner/analysis/parser/AnsibleLintParserTest.java, src/test/java/edu/hm/hafner/analysis/registry/ParsersTest.java, src/test/resources/edu/hm/hafner/analysis/parser/ansibleLint.txt
Ansible-lint now (tested with version 6.8.2) has rule names containing square brackets, like e.g. `fqcn[action]`. Updated the regular expression to support square brackets in rule names. Result output generated with the `--parseable` option can now again be parsed with the updated regular expression.
Related to the unmarked points above:
- I do not know any related issues, I have detected the issue on my system
- No relevant pull requests, upstream or downstream changes are known
=> Fix regular expression for ansible-lint to support rule names containing square brackets

src/main/java/edu/hm/hafner/analysis/parser/CodeCheckerParser.java, src/test/java/edu/hm/hafner/analysis/parser/CodeCheckerParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/CodeChecker_with_linux_paths.txt
CodeChecker can output UNSPECIFIED as a warning level when it does not know the level fully. For example here: https://github.com/Ericsson/codechecker/blob/36e6ad8c9a7381545983e89ebe756f6493bcd503/web/client/codechecker_client/report_type_converter.py#L86
This extends what was added here: https://github.com/jenkinsci/analysis-model/pull/706
=> Add UNSPECIFIED and STYLE as a output from CodeChecker

pom.xml
Property interpolation for the `<url>` tag in the `<repository>` tag has been banned in maven 4. This PR inlines the incrementals URL to comply with the upcoming restriction.
=> Inline incrementals URL

src/main/java/edu/hm/hafner/analysis/parser/PolyspaceParser.java, src/test/java/edu/hm/hafner/analysis/parser/PolyspaceParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/polyspace.csv, src/test/resources/edu/hm/hafner/analysis/parser/polyspace_cp.csv
Updated the parser file with Integer.valueOf() function for column and line set, since line number was showing as 0 for all issues in the dashboard. 
Also updated the logic of checking whether it is a BugFinder or a CodeProver file to be based on the header. (Test file edited accordingly) 
Relevant pull request : https://github.com/jenkinsci/warnings-ng-plugin/pull/1412
=> Fix parsing of line and column numbers in Polyspace parser

SUPPORTED-FORMATS.md, src/main/java/edu/hm/hafner/analysis/IssueBuilder.java, src/main/java/edu/hm/hafner/analysis/parser/JsonBaseParser.java, src/test/java/edu/hm/hafner/analysis/IssueBuilderTest.java, src/test/java/edu/hm/hafner/analysis/parser/JsonLogParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/JsonParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/XmlParserTest.java
Fix for [#70498](https://issues.jenkins.io/browse/JENKINS-70498)
Changed the test case in `JSONParserTest` class to read the first element of `lineRanges` list, which initially failed the test. Changed the `JSONBaseParser` to initialise `lineStart` and `lineEnd` of the `IssueBuilder` by reading the first element of `lineRanges` list.
=> [JENKINS-70498] Correctly handle line ranges in the JSONParser

pom.xml, src/main/java/edu/hm/hafner/analysis/FingerprintGenerator.java, src/main/java/edu/hm/hafner/analysis/Report.java, src/test/java/edu/hm/hafner/analysis/ReportTest.java
Do not use format method when simply copying log messages.
Fixes [JENKINS-70804](https://issues.jenkins.io/browse/JENKINS-70804)
=> [JENKINS-70804] Do not use format method when simply copying log messages

src/main/java/edu/hm/hafner/analysis/Issue.java, src/main/java/edu/hm/hafner/analysis/parser/AbstractMavenLogParser.java, src/main/java/edu/hm/hafner/analysis/parser/JavaDocParser.java, src/main/java/edu/hm/hafner/analysis/parser/JavacParser.java, src/main/java/edu/hm/hafner/analysis/parser/MavenConsoleParser.java, src/test/java/edu/hm/hafner/analysis/IssueTest.java, src/test/java/edu/hm/hafner/analysis/parser/AntJavacParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/JavaDocParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/MavenConsoleParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/javadoc-in-java.log, src/test/resources/edu/hm/hafner/analysis/parser/maven.3.9.1.log
Since maven 3.9.0 log messages that log a plugin name in the style `maven-compiler-plugin` are now abbreviated with `compiler`. This PR allows both formats. Additionally, the parser has been improved so that JavaDoc warnings are skipped for the Java parser, and vice versa.
Fixes:
- https://issues.jenkins.io/browse/JENKINS-70658
- https://issues.jenkins.io/browse/JENKINS-67521
- https://issues.jenkins.io/browse/JENKINS-63346
Supersedes:
- #900
- #897
=> Add support for Maven 3.9.x log messages

src/main/java/edu/hm/hafner/analysis/parser/AquaScannerParser.java, src/test/java/edu/hm/hafner/analysis/parser/AquaScannerParserTest.java
This PR introduces severity remapping for Aqua scanner as severities became inconsistent with Trivy scanner severities following [this pr](https://github.com/jenkinsci/analysis-model/pull/823).
Note that Aqua has additional severities like malware and sensitive (exposed credentials) which are now mapped to ERROR severity as I think that they need to be distinguished in a similar way as critical severity. 
Old mapping:
-   Critical -> High
-   Malware -> High
-   Sensitive -> High
-   High -> High
-   Medium -> Normal
-   Low -> Low
-   Negligible -> Low
New mapping
-   Critical -> Error
-   Malware -> Error
-   Sensitive -> Error
-   High -> High
-   Medium -> Normal
-   Low -> Low
-   Negligible -> Low
=> Remap Aqua scanner severities

src/main/java/edu/hm/hafner/analysis/parser/AbstractMavenLogParser.java, src/main/java/edu/hm/hafner/analysis/parser/JavacParser.java, src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/kotlin-1_8.txt
with kotlin 1.8 they changed the compile warnings style.
Old style `<package-name><filename>.kt: (line,column)`
new style `<package-name><filename>.kt:line:column`
to archive this we need to make the `(`, `)˙ and `[`, `]` optional as well ad a new separator `:` 
```[tasklist]
```
=> Fix kotlin 1.8 warnings not detected

pom.xml
This will use all available cores to run tests, and parallelize by all - suite/class/method. On machines with multiple cores, this will vastly improve test performance. These times are on my M1 MBP with 10 (8P + 2E) cores. They were reported by maven on running `mvn verify`.
I first ran `mvn verify` and ignored the time.
Then I ran it thrice without this change, and thrice with this change.
All times in seconds.
|        | Run 1 | Run 2 | Run 3 | Average |
| ------ | ----: | ----: | ----: | ------: |
| Before |    74 |    72 |    73 |      73 |
| After  |    68 |    68 |    68 |      68 |
| Savings|       |       |       |       5 |
| %      |       |       |       |       7 |
All existing tests run
```[tasklist]
```
=> Parallelize Tests

SUPPORTED-FORMATS.md, src/main/java/edu/hm/hafner/analysis/registry/PyLintDescriptor.java
The `msg-template` setting only works in the pylintrc configuration file if it is under the `[REPORTS]` section header [0]. Otherwise the setting gets ignored:
```
$ cat ./pylintrc
msg-template={path}:{module}:{line}: [{msg_id}({symbol}), {obj}] {msg}
$ pylint --rcfile=./pylintrc test.py
************* Module pylintrc
pylintrc:1:0: F0011: error while parsing the configuration: File contains no section headers.
file: 'pylintrc', line: 1
'msg-template={path}:{module}:{line}: [{msg_id}({symbol}), {obj}] {msg}\n' (config-parse-error)
[...]
```
Using the `--msg-template` CLI option is more convenient for the usage inside Jenkins pipelines.
[0]: https://github.com/pylint-dev/pylint/blob/v2.17.4/examples/pylintrc#L481
---
Related Jira issue: https://issues.jenkins.io/browse/JENKINS-71665
TODO: …
=> Update the help text for the Pylint descriptor

pom.xml, src/main/java/edu/hm/hafner/analysis/parser/ClangAnalyzerPlistParser.java, src/main/java/edu/hm/hafner/analysis/parser/FlawfinderParser.java, src/main/java/edu/hm/hafner/analysis/parser/IdeaInspectionParser.java, src/main/java/edu/hm/hafner/analysis/parser/StyleCopParser.java, src/main/java/edu/hm/hafner/analysis/parser/XmlParser.java, src/test/java/edu/hm/hafner/analysis/ArchitectureTest.java, src/test/java/edu/hm/hafner/analysis/parser/IdeaInspectionParserTest.java, src/test/resources/archunit_ignore_patterns.txt, src/test/resources/edu/hm/hafner/analysis/parser/issue56235.xml
This pull request was created regarding following issues:
https://issues.jenkins.io/browse/JENKINS-71687
also on
https://youtrack.jetbrains.com/issue/IDEA-325906/IDEA-Inspections-cause-Exception-during-Jenkins-Job
The Idea-Inspection of the new Idea-Versions doesn't return a line-number, which causes an Error in the parseInt function (For details see Issue JENKINS-71687) ->
So I made the issueBuilder.setLineStart(Integer.parseInt(getChildValue(element, "line"))); optional.
I added a problem to the issue56235.xml, which gets tested in the IdeaInspectionParserTest.java.
```[tasklist]
```
=> [JENKINS-71687] Intellij IDEA Inspection causes Exception during Jenkins Job fix

SUPPORTED-FORMATS.md, src/main/java/edu/hm/hafner/analysis/parser/CrossCoreEmbeddedStudioParser.java, src/main/java/edu/hm/hafner/analysis/registry/CrossCoreEmbeddedStudioDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java, src/test/java/edu/hm/hafner/analysis/parser/CrossCoreEmbeddedStudioParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/cces.log
Add support for parsing compiler logs generated by CrossCore Embedded Studio.
- Implementation inspired from `Gcc4CompilerParser.java` and `EmbeddedEngineerParser.java`
- Compiler errors are not parsed, only warnings. Could be improved in a second stage
- Added relatively extensive tests in `CrossCoreEmbeddedStudioParserTest.java` 
- https://github.com/jenkinsci/warnings-ng-plugin/pull/1566
Not clear to me how to  _"run `main` method of `ParserRegistry`"_. Where is the binary? (Note that my java level is extremely low)
=> Add parser for CCES (CrossCore Embedded Studio)

src/main/java/edu/hm/hafner/analysis/parser/dry/AbstractDryParser.java, src/main/java/edu/hm/hafner/analysis/parser/dry/cpd/CpdParser.java, src/main/java/edu/hm/hafner/analysis/parser/dry/dupfinder/DupFinderParser.java, src/main/java/edu/hm/hafner/analysis/parser/dry/simian/SimianParser.java, src/test/java/edu/hm/hafner/analysis/parser/dry/cpd/CpdParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/dry/dupfinder/DupFinderParserTest.java, src/test/java/edu/hm/hafner/analysis/parser/dry/simian/SimianParserTest.java
I have noticed that there were no category nor type on cpd issues, which impact their integration with other tools.
In the category tab on Jenkins, it render a blank line which make them non clickable.
In the type tab, they are rendered with a `-` and gathered with all the other categorized issues.
And in the issue tab they are not easily identifiable without category nor type
So I proposed to set for all cpd issues a category `CPD` and for type `CodeDuplication`
```[tasklist]
```
=> Add category and type to code duplication issues

Jenkinsfile, SUPPORTED-FORMATS.md, pom.xml
Move the definition of parallel testing from the Maven pom file into the Jenkinsfile so that ci.jenkins.io continues to run the tests with one process per available core, while developers are allowed to configure the amount of parallel testing based on the configuration and use of their computer.
Developers can adjust parallel execution by passing a command line argument to Maven like this:
```bash
mvn clean -DforkCount=1C verify
```
Developers can define a Maven profile that sets the forkCount in their
~/.m2/settings.xml like this:
```xml
<profile>
<id>faster</id>
<activation>
<activeByDefault>true</activeByDefault>
</activation>
<properties>
<forkCount>.45C</forkCount>
</properties>
</profile>
```
With that entry in the settings.xml file, then 0.45C will be used for:
```bash
mvn clean …
```
=> Allow developer control of parallel testing

src/main/java/edu/hm/hafner/analysis/parser/AbstractMavenLogParser.java, src/main/java/edu/hm/hafner/analysis/parser/MavenConsoleParser.java, src/test/java/edu/hm/hafner/analysis/parser/MavenConsoleParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/enforcer-empty.txt, src/test/resources/edu/hm/hafner/analysis/parser/issue72011.txt
Add a guard before reading additional info messages to the buffer.
See [JENKINS-72011](https://issues.jenkins.io/browse/JENKINS-72011) for details.
=> [JENKINS-72011] Do not read from empty stream

SUPPORTED-FORMATS.md, etc/Jenkinsfile.valgrind, src/main/java/edu/hm/hafner/analysis/parser/violations/ValgrindAdapter.java, src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java, src/main/java/edu/hm/hafner/analysis/registry/ValgrindDescriptor.java, src/test/java/edu/hm/hafner/analysis/parser/violations/ValgrindAdapterTest.java, src/test/resources/edu/hm/hafner/analysis/parser/violations/valgrind.xml
This is the beginning of a [valgrind](https://valgrind.org) report parser.  It is a work-in-progress based on the [recent addition](https://github.com/tomasbjerre/violations-lib/pull/138) of a valgrind parser to [violations-lib](https://github.com/tomasbjerre/violations-lib) so it depends upon #735 and will fail CI until that is merged because I didn't want to conflict the pom.xml changes for that here.  The eventual goal of this pull request is to provide valgrind support in warnings-ng as a replacement for the broken, vulnerable, and unmaintained jenkins [valgrind-plugin](https://github.com/jenkinsci/valgrind-plugin).
There are a few known problems/open questions with this that I could use some advice/help with to move this forward.  I'm willing to work this through whatever needs to be …
=> Add valgrind parser

src/main/java/edu/hm/hafner/analysis/parser/MsBuildParser.java, src/test/java/edu/hm/hafner/analysis/parser/MsBuildParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/issue63580.txt
Closes JENKINS-63580
```[tasklist]
```
=> [JENKINS-63580] Update regex for msbuild to recognize linker warnings

CONTRIBUTING.md
`CONTRIBUTING.md` was referencing the base branch as `master`, but it is named `main`. Updated the markdown file accordingly.
=> Change base branch name in CONTRIBUTING.md

SUPPORTED-FORMATS.md, doc/dependency-graph.puml, pom.xml
Use maven central for deployments of releases.
=> Use ossrh for deployments

src/main/java/edu/hm/hafner/analysis/registry/CodeGeneratorDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/CrossCoreEmbeddedStudioDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/EmbeddedEngineerDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/FindBugsDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/GrypeDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/OwaspDependencyCheckDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/PnpmAuditDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/PolyspaceDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/RevApiDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/SimulinkCheckDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/ValgrindDescriptor.java
As discussed in https://github.com/jenkinsci/analysis-model/pull/972#issuecomment-1790981252 the descriptor classes are not intended to be public.
This MR makes it consistent between all the descriptor classes.
=> Make descriptor classes package protected

SUPPORTED-FORMATS.md, src/main/java/edu/hm/hafner/analysis/registry/PmdDescriptor.java
Update PMD logo location in SUPPORTED-FORMATS.md
Only markdown related changes, checking if logo is again displayed:
```[tasklist]
```
=> Update PMD logo location in SUPPORTED-FORMATS.md

src/main/java/edu/hm/hafner/analysis/parser/GrypeParser.java, src/test/java/edu/hm/hafner/analysis/parser/GrypeParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/grype-report.json
The warnings-ng reports for Grype are missing important information, namely the vulnerable artifact's name and its type. This makes it difficult to see the affected packages when reviewing the report as the file path often doesn't contain the artifact name (e.g. for RPMs in a Docker image the file path reported by Grype is just "/var/lib/rpm/Packages"; only the artifact name reveals the actual RPM name like curl etc.).
This PR adds the artifact name from the Grype JSON report as package name and changes the report's category to the artifact type (instead of duplicating the severity information there). I chose package over module name as the package is visible in the warnings-ng issue list while the module isn't.
The existing JUnit test for the GrypeParser has been adjusted to also verify …
=> GrypeParser: added artifact name and type to report

src/main/java/edu/hm/hafner/analysis/parser/AbstractMavenLogParser.java, src/main/java/edu/hm/hafner/analysis/parser/JavacParser.java, src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/issue72077.txt
See [JENKINS-72077](https://issues.jenkins.io/browse/JENKINS-72077) for details.
=> [JENKINS-72077] Ignore warnings from surefire and failsafe plugins

src/main/java/edu/hm/hafner/analysis/IssueBuilder.java, src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/kotlin-cmake.txt
For projects with a mixture of Kotlin and CMake compiles the output of both can be mixed depending on the order of the tasks. The working path defined by the CMake output should not be used for warnings which already print out absolute paths e.g. Kotlin warnings. It should only be used if the path is a relative path.
```[tasklist]
```
=> Fix parsing for mixture of Kotlin and CMake output

src/main/java/edu/hm/hafner/analysis/parser/EmbeddedEngineerParser.java, src/test/java/edu/hm/hafner/analysis/parser/EmbeddedEngineerParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/ea.log
Current implementation does not take warnings in the following structure into account:
[2024-01-05 10:52:27.3199] Warn - Out parameters ('Model_ptr_2345') are not supported. Please use 'return' or 'inout' parameters; {98CF1FE6-EC9C-43f1-e476-40EFCD63cA8D}
For this purpose only the WARNING_PATTERN was modified to capture new category. 
The current change was tested by adding additional test case to the EmbeddedEngineerParserTest file.
Tests were executed using [warnings-ng-plugin-devenv] development environment. 
Screenshots of the test results:
=> [EA] Add support for categories separated by a brace

src/main/java/edu/hm/hafner/analysis/parser/violations/CodeClimateAdapter.java, src/main/java/edu/hm/hafner/analysis/registry/CodeClimateDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java, src/test/java/edu/hm/hafner/analysis/parser/violations/CodeClimateAdapterTest.java, src/test/resources/edu/hm/hafner/analysis/parser/violations/code-climate.json
=> Add support for Code Climate

src/main/java/edu/hm/hafner/analysis/FingerprintGenerator.java, src/test/java/edu/hm/hafner/analysis/FingerprintGeneratorTest.java
For files with extension `"o", "exe", "dll", "so", "a", "lib", "jar", "war", "zip", "7z", "gz", "bz2"` it does not make sense to compute a fingerprint.
See [JENKINS-68415](https://issues.jenkins.io/browse/JENKINS-68415)
=> [JENKINS-68415] Skip archives, jar-files and executables from fingerprinting

src/main/java/edu/hm/hafner/analysis/IssueDifference.java, src/test/java/edu/hm/hafner/analysis/IssueDifferenceTest.java
Followup for #1005.
Otherwise we cannot show the different issue types in the UI.
=> Mark issues that are part of changed code in the issue difference

doc/dependency-graph.puml, src/main/java/edu/hm/hafner/analysis/Issue.java, src/main/java/edu/hm/hafner/analysis/IssueDifference.java, src/main/java/edu/hm/hafner/analysis/IssuesInModifiedCodeMarker.java, src/main/java/edu/hm/hafner/analysis/LineRange.java, src/test/java/edu/hm/hafner/analysis/IssueDifferenceTest.java, src/test/java/edu/hm/hafner/analysis/IssuesInModifiedCodeMarkerTest.java, src/test/java/edu/hm/hafner/analysis/LineRangeTest.java
It makes more sense to use a flag to mark the issues that are part of modified code. 
Replaces the implementations of
- #1006 
- #1005
=> Use a flag to mark the issues that are part of modified code

src/main/java/edu/hm/hafner/analysis/Report.java, src/test/java/edu/hm/hafner/analysis/ReportTest.java
When there is no difference yet we still need to set the reference for all issues.
=> Add a setter for the reference

.github/workflows/update-badges.yml, SUPPORTED-FORMATS.md, src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java, src/test/java/edu/hm/hafner/analysis/registry/ParserRegistryTest.java, src/test/java/edu/hm/hafner/analysis/registry/UpdateSupportedFormats.java
This will bring the list of supported formats automatically up-to-date.
=> Automatically update supported formats after each commit

src/main/java/edu/hm/hafner/analysis/IssueBuilder.java, src/main/java/edu/hm/hafner/analysis/parser/ClangParser.java, src/test/java/edu/hm/hafner/analysis/parser/ClangParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/llvm-clang.txt
The prefix was detected as part of the file name
leading to a java.nio.file.InvalidPathException
in IssueBuilder.isAbsolutePath().
In addition to fixing the path parsing in ClangParser
the Exception thrown in the IssueBuilder.isAbsolutePath()
is also catched.
```[tasklist]
```
=> Fix parsing of clang warnings with "C/C++:" prefix

src/main/java/edu/hm/hafner/analysis/FingerprintGenerator.java, src/test/java/edu/hm/hafner/analysis/FingerprintGeneratorTest.java
Processing file names with colons will produce a IAE omn Windows: those files can be ignored during fingerprinting.
```
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 23d30129-9137-4261-a261-7f362ba83618 java.lang.IllegalArgumentException: NTFS ADS separator (':') in file name is forbidden.
at org.apache.commons.io.FilenameUtils.indexOfExtension(FilenameUtils.java:955)
at org.apache.commons.io.FilenameUtils.getExtension(FilenameUtils.java:614)
at edu.hm.hafner.analysis.FingerprintGenerator.hasAllowedExtension(FingerprintGenerator.java:56)
at edu.hm.hafner.analysis.FingerprintGenerator.run(FingerprintGenerator.java:43)
at io.jenkins.plugins.analysis.core.steps.IssuesScanner$ReportPostProcessor.createFingerprints(IssuesScanner.java:363)
at …
```
=> Ignore files that cause an exception while determining the prefix

src/main/java/edu/hm/hafner/analysis/registry/PmdDescriptor.java
Use the square logo of PMD that provides a better scaling result. This icon still provides a poor rendering for actions (20x20) but it is better than the old one.
Before: 
After:
=> Use the PMD square image.

pom.xml, src/main/java/edu/hm/hafner/analysis/parser/violations/CoverityAdapter.java, src/main/java/edu/hm/hafner/analysis/registry/CoverityDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java, src/test/java/edu/hm/hafner/analysis/parser/violations/CoverityAdapterTest.java, src/test/java/edu/hm/hafner/analysis/registry/AbstractParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/violations/coverity.json
Add support for [Coverity](https://scan.coverity.com/) JSON reports.
```[tasklist]
```
=> [JENKINS-72887] Add coverity parser

src/main/java/edu/hm/hafner/analysis/Report.java, src/test/java/edu/hm/hafner/analysis/ReportTest.java
Example duplication:
```
Parsing console log (workspace: '/var/data/workspace/history-coverage-model')
Successfully parsed console log
-> found 0 issues (skipped 0 duplicates)
Skipping post processing
No filter has been set, publishing all 0 issues
Extracting repository forensics for 0 affected files (files in repository: 184)
-> 0 affected files processed
Successfully parsed console log
-> found 0 issues (skipped 0 duplicates)
Successfully parsed console log
-> found 0 issues (skipped 0 duplicates)
Successfully parsed console log
-> found 0 issues (skipped 0 duplicates)
Parsing console log (workspace: '/var/data/workspace/history-coverage-model')
Skipping post processing
No filter has been set, publishing all 0 issues
Extracting repository forensics for 0 affected files (files in …
```
=> Skip subreport messages when copying and merging reports

src/main/java/edu/hm/hafner/analysis/parser/ProtoLintJsonParser.java, src/main/java/edu/hm/hafner/analysis/parser/ProtoLintParser.java, src/main/java/edu/hm/hafner/analysis/registry/ProtoLintDescriptor.java, src/test/java/edu/hm/hafner/analysis/parser/ProtoLintJsonParserTest.java, src/test/java/edu/hm/hafner/analysis/registry/ParsersTest.java, src/test/resources/edu/hm/hafner/analysis/parser/protolint_0.49.8.json, src/test/resources/edu/hm/hafner/analysis/parser/protolint_0.50.2.json
Pull request for https://issues.jenkins.io/browse/JENKINS-73363
Plaintext format is still supported. Unit test was added.
=> [JENKINS-73363] Add support for protoLint JSON format

pom.xml
Fix POM flattening configuration: now all artifacts are correctly added to the list of dependencies.
See [JENKINS-73663](https://issues.jenkins.io/browse/JENKINS-73663)
=> [JENKINS-73663] Fix pom flattening so that parent deps are included now

src/main/java/edu/hm/hafner/analysis/parser/YoctoScannerParser.java, src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java, src/main/java/edu/hm/hafner/analysis/registry/YoctoScannerDescriptor.java, src/test/java/edu/hm/hafner/analysis/parser/YoctoScannerParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/yocto_scanner_result.json
Yocto project support CVE security vulnerabilities using cve-check in the specific image or target you are building, add the following setting to your configuration:
INHERIT += "cve-check"
status of each CVE: Patched, Unpatched or Ignored
The scanner look only for Unpatched package and calculate the severity using the score_v2 or score_v3
Deployed in internal company jenkins infrastructure and verify on real yocto product
=> Add support for Yocto scanner

src/main/java/edu/hm/hafner/analysis/registry/ClairDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/CodeCheckerDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/DryDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/ErrorProneDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/FindBugsDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/FlawfinderDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/OwaspDependencyCheckDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/ParserDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/ParserRegistry.java, src/main/java/edu/hm/hafner/analysis/registry/PnpmAuditDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/SemgrepDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/SpotBugsDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/TrivyDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/YoctoScannerDescriptor.java, src/main/java/edu/hm/hafner/analysis/registry/ZptLintDescriptor.java, src/test/java/edu/hm/hafner/analysis/registry/ParserRegistryTest.java
The plugin started with warnings only, but now we can scan for warnings, bugs, vulnerabilities, etc. It makes sense to categorize all parsers so we can automatically set icons and texts for the selected parser.
=> Add parser categories

src/main/java/edu/hm/hafner/analysis/parser/violations/AbstractViolationAdapter.java, src/main/java/edu/hm/hafner/analysis/parser/violations/SarifAdapter.java, src/test/java/edu/hm/hafner/analysis/parser/violations/SarifAdapterTest.java, src/test/resources/edu/hm/hafner/analysis/parser/violations/brokenfilePath.sarif, src/test/resources/edu/hm/hafner/analysis/parser/violations/emptyfilePath.sarif, src/test/resources/edu/hm/hafner/analysis/parser/violations/filePathInFileUriScheme.sarif
see https://issues.jenkins.io/browse/JENKINS-73933
file paths in file uri scheme are converter to normal paths
=> Sarif report: allow file paths in file URI scheme

pom.xml, src/test/java/edu/hm/hafner/analysis/parser/AntJavacParserTest.java
Make the build more robust:
- Remove dependency check: this is part of a profile now (parent pom)
- Increase timeout for test of JENKINS-55805
=> Fix timeout problems in CI

src/main/java/edu/hm/hafner/analysis/parser/violations/SarifAdapter.java, src/test/java/edu/hm/hafner/analysis/parser/violations/SarifAdapterTest.java, src/test/resources/edu/hm/hafner/analysis/parser/violations/suppressed-sarif.json
Ignore suppressions in SARIF reports, as them being suppressed should exclude them from the violations, and related quality gates in the warnings ng plugin 
Unit tests were updated and was run against a jenkins instance passing in a sarif file with suppressions, which were ignored correctly
=> Ignore suppressed issues in sarif reports

src/main/java/edu/hm/hafner/analysis/parser/SimulinkCheckParser.java, src/test/java/edu/hm/hafner/analysis/parser/SimulinkCheckParserTest.java
This pull request fixes the issue with the SimulinkCheckParser where model file extensions (e.g., .slx, .mdl , etc) were missing in the filenames passed to the IssueBuilder. Previously, the parser extracted only the model name without its extension, causing fingerprinting errors during processing of Simulink Check Tool reports.  (https://issues.jenkins.io/browse/JENKINS-72838)
Created a freestyle Project and parsed a static html report with the model present in the workspace.
=> Fixes SimulinkCheckParser fingerprinting issue

pom.xml, src/main/java/edu/hm/hafner/analysis/Report.java, src/test/java/edu/hm/hafner/analysis/ReportTest.java
This part of the code was used as example only.
=> Remove issue printer

src/main/java/edu/hm/hafner/analysis/parser/JavacParser.java, src/test/java/edu/hm/hafner/analysis/parser/JavacParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/issue70153.txt
[Closes](https://issues.jenkins.io/browse/JENKINS-70153)
Added support for gradle build-tools warnings (w:) by modifying the Pattern in the `JavacParser`. Now it matches the filename/line format along with quoted messages as mentioned in the issue.
=> [Jenkins-70153] Add support for gradle build-tools warnings (w:)

pom.xml
RevApi compares our code to the latest released version of this library. To find this version, it depends on the artifacts deployed to Maven repositories. Unfortunately, the analysis-model is released in two different repositories, making it impossible to auto-detect. Therefore, we need to write the latest version into the POM (during the release process) and provide this version as property for RevApi.
Fixes jenkins-infra/helpdesk#4543
=> Write the latest version of the library as property into the POM

src/main/java/edu/hm/hafner/analysis/parser/DoxygenParser.java, src/main/java/edu/hm/hafner/analysis/parser/Gcc4CompilerParser.java, src/test/java/edu/hm/hafner/analysis/parser/DoxygenParserTest.java, src/test/resources/edu/hm/hafner/analysis/parser/issue61855.txt
FIXES - [JENKINS-61855](https://issues.jenkins.io/browse/JENKINS-61855)
Added Support for Doxygen Warnings having format -
`file_path(line):col: Warning/Error: message` along with the existing format - 
`file_path:line:col: Warning/Error: message`
=> [JENKINS-61855] Add Support for Doxygen Warnings.

src/main/java/edu/hm/hafner/analysis/parser/AnsibleLintParser.java, src/test/java/edu/hm/hafner/analysis/parser/AnsibleLintParserTest.java, src/test/java/edu/hm/hafner/analysis/registry/ParsersTest.java, src/test/resources/edu/hm/hafner/analysis/parser/ansibleLint.txt
In ansible-lint it is possible to set a [`warn-list` for lower level warnings](https://ansible.readthedocs.io/projects/lint/usage/#ignoring-rules).
It is shown as such in parseable output with a [` (warning)` at the end of the line](https://github.com/ansible/ansible-lint/blob/3553b2a8126e31db0e61296961e4c1f8577386f6/src/ansiblelint/formatters/__init__.py#L102).
In SARIF output it is of level `warning` (instead of `error`).
So to be consistent, it is more logic to be parsed as `WARNING_LOW`, like the `warning` from SARIF.
This PR detect the presence of the final ` (warning)` and use it to lower the severity to `WARNING_LOW`.
As a bonus, this ` (warning)` is no more in the warning message.
Unit test for ansible-lint parser has been updated accordingly to the new parsing.
=> Handle levels of ansible-lint warnings

src/main/java/edu/hm/hafner/analysis/parser/MsBuildParser.java, src/test/java/edu/hm/hafner/analysis/parser/MsBuildParserTest.java
When a warning is identified in a C/C++ header file and this file is included in several source code files, then the warning appears for each distinct import. It makes more sense to skip those duplicates, and count such warnings only once.
We use a pragmatic fix to provide a solution for JENKINS-70855: we simply remove the offending "import" text to make the warnings equal to each other.
See [JENKINS-70855](https://issues.jenkins.io/browse/JENKINS-70855)
=> [JENKINS-70855] Skip duplicate warnings from imported header files

src/main/java/edu/hm/hafner/analysis/FileReaderFactory.java, src/main/java/edu/hm/hafner/analysis/ParsingException.java, src/main/java/edu/hm/hafner/analysis/ReaderFactory.java, src/main/java/edu/hm/hafner/analysis/parser/AbstractDryParser.java, src/main/java/edu/hm/hafner/analysis/parser/AjcParser.java, src/main/java/edu/hm/hafner/analysis/parser/CcmParser.java, src/main/java/edu/hm/hafner/analysis/parser/CheckStyleParser.java, src/main/java/edu/hm/hafner/analysis/parser/ClangAnalyzerPlistParser.java, src/main/java/edu/hm/hafner/analysis/parser/EclipseXmlParser.java, src/main/java/edu/hm/hafner/analysis/parser/EmbeddedEngineerParser.java, src/main/java/edu/hm/hafner/analysis/parser/FindBugsParser.java, src/main/java/edu/hm/hafner/analysis/parser/JcReportParser.java, src/main/java/edu/hm/hafner/analysis/parser/JsonIssueParser.java, src/main/java/edu/hm/hafner/analysis/parser/JsonParser.java, src/main/java/edu/hm/hafner/analysis/parser/PmdParser.java, src/main/java/edu/hm/hafner/analysis/parser/SimulinkCheckParser.java, src/main/java/edu/hm/hafner/analysis/parser/TaglistParser.java, src/main/java/edu/hm/hafner/analysis/parser/XmlParser.java, src/main/java/edu/hm/hafner/analysis/parser/violations/AbstractViolationAdapter.java, src/test/java/edu/hm/hafner/analysis/parser/PmdParserTest.java
When a file cannot be read, then the name of the file should be shown. This helps to find the root cause for the failure.
Before:
```
edu.hm.hafner.analysis.ParsingException: Input stream is not a PMD file.
at edu.hm.hafner.analysis.parser.PmdParser.parseIssues(PmdParser.java:65)
at edu.hm.hafner.analysis.parser.PmdParser.parseReport(PmdParser.java:39)
at edu.hm.hafner.analysis.IssueParser.parse(IssueParser.java:62)
at edu.hm.hafner.grading.FileSystemToolParser.readReport(FileSystemToolParser.java:40)
at edu.hm.hafner.grading.ScoreBuilder.readReport(ScoreBuilder.java:162)
at edu.hm.hafner.grading.AnalysisScore$AnalysisScoreBuilder.read(AnalysisScore.java:177)
at edu.hm.hafner.grading.AggregatedScore.grade(AggregatedScore.java:390)
at …
```
=> Show the filename when throwing an exception
